change_config:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: anything_llm_conversation
    api_key:
      selector:
        text:
          type: password
    base_url:
      example: http://localhost:3001/api
      selector:
        text:
